version: '3.8'

services:
  ai-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: willa-ai-server:latest
    container_name: willa-ai-server
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/static_temp:/app/backend/static_temp
    restart: always
